# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('danwei', models.CharField(blank=True, max_length=30)),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('mac', models.CharField(blank=True, max_length=30)),
                ('app', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
