# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('server', '服务器'), ('vmser', '虚拟机'), ('switch', '交换机'), ('route', '路由器'), ('printer', '打印机'), ('scanner', '扫描仪'), ('firewall', '防火墙'), ('storage', '存储设备'), ('wifi', '无线设备')], default='server', max_length=100, verbose_name='资产类型')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='资产编号')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备序列号')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='购买时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过保修期')),
                ('buy_user', models.SmallIntegerField(blank=True, null=True, verbose_name='购买人')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='制造商')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='供货商')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产型号')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='状态')),
                ('put_zone', models.SmallIntegerField(blank=True, null=True, verbose_name='放置区域')),
                ('group', models.SmallIntegerField(blank=True, null=True, verbose_name='使用组')),
                ('business', models.SmallIntegerField(blank=True, null=True, verbose_name='业务类型')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('can_read_assets', '读取资产权限'), ('can_change_assets', '更改资产权限'), ('can_add_assets', '添加资产权限'), ('can_delete_assets', '删除资产权限')),
                'verbose_name_plural': '总资产表',
                'db_table': 'opsmanage_assets',
                'verbose_name': '总资产表',
            },
        ),
        migrations.CreateModel(
            name='Server_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('keyfile', models.SmallIntegerField(blank=True, null=True)),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('line', models.SmallIntegerField(blank=True, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True)),
                ('vcpu_number', models.SmallIntegerField(blank=True, null=True)),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True)),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_total', models.IntegerField(blank=True, null=True)),
                ('kernel', models.CharField(blank=True, max_length=100, null=True)),
                ('selinux', models.CharField(blank=True, max_length=100, null=True)),
                ('swap', models.CharField(blank=True, max_length=100, null=True)),
                ('raid', models.SmallIntegerField(blank=True, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Assets')),
            ],
            options={
                'permissions': (('can_read_server_assets', '读取服务器资产权限'), ('can_change_server_assets', '更改服务器资产权限'), ('can_add_server_assets', '添加服务器资产权限'), ('can_delete_server_assets', '删除服务器资产权限')),
                'verbose_name_plural': '服务器资产表',
                'db_table': 'opsmanage_server_assets',
                'verbose_name': '服务器资产表',
            },
        ),
        migrations.CreateModel(
            name='User_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.SmallIntegerField(verbose_name='服务器资产id')),
                ('user_id', models.SmallIntegerField(verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '用户服务器表',
                'db_table': 'opsmanage_user_server',
                'permissions': (('can_read_user_server', '读取用户服务器表权限'), ('can_change_user_server', '更改用户服务器表权限'), ('can_add_user_server', '添加用户服务器表权限'), ('can_delete_user_server', '删除用户服务器表权限')),
                'verbose_name': '用户服务器表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user_server',
            unique_together=set([('server_id', 'user_id')]),
        ),
    ]
